/**
 * Created by leibo on 18/1/2.
 */
export default {
  sidebar: state => state.app.sidebar,
  device: state => state.app.device,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  roles: state => state.user.roles,
  //------------管理员----------
  transtionActive: state => state.transtionActive,
  isAgencies: state => state.isAgencies,
  isFood: state => state.isFood,
  isHotel: state => state.isHotel,
  isTickets: state => state.isTickets,
  isCar: state => state.isCar,
  isAdvertising: state => state.isAdvertising,
  isMovie: state => state.isMovie,
  adminTradeGoodList: state => state.adminTradeGoodList,
  queryUserOrderList: state => state.queryUserOrderList,
  searchUserOrderList: state => state.searchUserOrderList,
  updateAdminTimeActivitiesObj: state => state.updateAdminTimeActivitiesObj,
  updateAdminQueryProductInformationObj: state => state.updateAdminQueryProductInformationObj,
  updateAdminScheduleTimeObj: state => state.updateAdminScheduleTimeObj,
  groupTourList: state => state.groupTourList,
  updateAdminGroupTourObj: state => state.updateAdminGroupTourObj,
  homeAdminGroupTourList: state => state.homeAdminGroupTourList,
  adminBusinessInformationList: state => state.adminBusinessInformationList,
  updateAdminBusinessInformationObj: state => state.updateAdminBusinessInformationObj,
  updateAdminMerchantProductsObj: state => state.updateAdminMerchantProductsObj,
  updateAdminLinePrepareObj: state => state.updateAdminLinePrepareObj,
  adminProductMenuList: state => state.adminProductMenuList,
  updateMenuObj: state => state.updateMenuObj,
  adminProductLine: state => state.adminProductLine,
  adminLinePrepare: state => state.adminLinePrepare,
  adminProductFeaturesList: state => state.adminProductFeaturesList,
  updateAdminProductFeaturesObj: state => state.updateAdminProductFeaturesObj,
  adminEventDiningList: state => state.adminEventDiningList,
  updateAdminActiveFoodObj: state => state.updateAdminActiveFoodObj,
  adminActiveHotelList: state => state.adminActiveHotelList,
  adminScheduleTimeList: state => state.adminScheduleTimeList,
  adminTimeActivitiesList: state => state.adminTimeActivitiesList,
  adminActivitySiteList: state => state.adminActivitySiteList,
  updateAdminActiveHotelObj: state => state.updateAdminActiveHotelObj,
  adminActiveReminderList: state => state.adminActiveReminderList,
  updateAdminActivitySiteObj: state => state.updateAdminActivitySiteObj,
  adminEventShoppingList: state => state.adminEventShoppingList,
  updateAdminEventShoppingObj: state => state.updateAdminEventShoppingObj,
  updateAdminActiveReminderObj: state => state.updateAdminActiveReminderObj,
  adminActiveTrafficList: state => state.adminActiveTrafficList,
  updateAdminActiveTrafficObj: state => state.updateAdminActiveTrafficObj,
  adminCostsOfList: state => state.adminCostsOfList,
  updateAdminCostsOfObj: state => state.updateAdminCostsOfObj,
  adminSystemMenuList: state => state.adminSystemMenuList,
  updateAdminSystemMenuObj: state => state.updateAdminSystemMenuObj,
  adminBusinessLicenseList: state => state.adminBusinessLicenseList,
  updateAdminBusinessLicenseObj: state => state.updateAdminBusinessLicenseObj,
  adminCommentsTypeList: state => state.adminCommentsTypeList,
  departureCityList: state => state.departureCityList,
  adminLinePriceList: state => state.adminLinePriceList,
  updateAdminLinePriceObj: state => state.updateAdminLinePriceObj,
  proviceList: state => state.proviceList,
  cityList: state => state.cityList,
  adminRouteDepartureCity: state => state.adminRouteDepartureCity,
  updateAdminRouteDepartureCityObj: state => state.updateAdminRouteDepartureCityObj,
  adminSupplierList: state => state.adminSupplierList,
  adminSupplierListObj: state => state.adminSupplierListObj,
  changeScopeOfOperationList: state => state.changeScopeOfOperationList,
  changeCompanyTypeList: state => state.changeCompanyTypeList,
  changeMineyTypeList: state => state.changeMineyTypeList,
  changeCooperationTypecList: state => state.changeCooperationTypecList,
  adminPersonalBenefitsList: state => state.adminPersonalBenefitsList,
  lookList: state => state.lookList,


  provinceDataList: state => state.provinceDataList,
  cityDataList: state => state.cityDataList,
  countyDataList: state => state.countyDataList,
  carCityPlaceList: state => state.carCityPlaceList,
  //参数
  adminMerchantProductsId: state => state.adminMerchantProductsId,
  adminProductLineManagementId: state => state.adminProductLineManagementId,
  adminProductCharacteristicManagementId: state => state.adminProductCharacteristicManagementId,
  adminLineScheduleManagementId: state => state.adminLineScheduleManagementId,
  adminScheduleTimeManagementId: state => state.adminScheduleTimeManagementId,
  adminTimeActivityManagementId: state => state.adminTimeActivityManagementId,
  adminActivityMealManagementId: state => state.adminActivityMealManagementId,
  //旅行社
  TravelAgencyOrderList: state => state.TravelAgencyOrderList,
}
